### ISSUE TITLE
Add an option to change cursor with resource packs

### ISSUE THREAD

**Issue by Vi-Tul** [JumperOnJava/CustomCursor-comm#1]
For example, create a built-in resource pack so players can change it as they want. For now (as I understand) you can only select from vanilla Minecraft textures. 

P.S.: I found this mod on CurseForge, but there were no "Source" tab. Сould you add this repository on the mod page so users don't have to do research to submit new issue?

**Comment by JumperOnJava** [comment]
You can add textures in resource packs already, you just have to write correct texture path

I don't have control over cf page, i will ask project owner ro add source code link

**Comment by Vi-Tul** [comment]
Yeah, I've found "cursor64" etc., but it would be nice to have some sort of guide for players to make custom resourcepacks. Thank you anyway for this mod!
