### ISSUE TITLE
Crash on startup - NeoForge 47.1.79 (1.20.1)

### ISSUE THREAD

**Issue by spunchbop121** [JumperOnJava/CustomCursor-comm#2]
crash-2023-11-06_18.57.45-client.txt - https://pastebin.com/VM1yteLh

crash-2023-11-06_18.57.42-fml.txt - https://pastebin.com/Ggntt4q9

**Comment by JumperOnJava** [comment]
Thanks for so quick response after update! Can you please send me your config file?

**Comment by JumperOnJava** [comment]
whoops closed accidentally

**Comment by spunchbop121** [comment]
> Thanks for so quick response after update! Can you please send me your config file?

https://pastebin.com/a9ct78q5

**Comment by JumperOnJava** [comment]
try deleting the config and check if it keeps crashing (and also send result here). I tried to launch mod on neoforge with your config but it works fine for me
